version: '3'

services:
  stash-yeezus-season:
    build:
      context: ./docker/service
      dockerfile: Dockerfile
    environment:
      PORT: 4535
    ports:
      - 4535:4535
    expose:
      - 4535
